version: '3'

services:
  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
      
  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    depends_on:
      - db
    environment:
      PMA_HOST: db	
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8092:80"

  air-quality-back:
    build:
      context: .  
    container_name: air-quality-back
    depends_on:
      - db
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/air_quality
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  dbdata:
    driver: local
